networks:
  main:
    name: fast-http
    driver: bridge
    ipam:
      config:
          - subnet: 179.25.0.0/24
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/init-es.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - main